### ISSUE TITLE
[Suggestion] Add immobilization for all dangerous monsters

### ISSUE THREAD

**Issue by ttmahik** [LegaSource/BetterFlashlight#1]
If it would not be difficult, add the ability to be able to disarm monsters like bracken, Buncker spider, Baboon Hawk, Thumper and Nutcracker, which will shoot in all directions for some time after he was blinded 
Your mod is pretty good and with hardcore play this mod will diversify the game a lot. I hope you don't abandon this mod and keep improving it
It would also be more convenient if it was possible to separately customize on whom the dazzle can affect

**Comment by LegaSource** [comment]
In the latest update, there's the possibility to add monsters to an exclusion list so they won't be affected by the flashlight
Another option has been added to configure all values per enemy but monsters without a stun animation or an 'eye' component won't be affected by default
For immobilization, I'm not entirely sure what you mean, because the mod does immobilize monsters when they're stunned
Regarding Nutcrackers, it would be illogical for them to be able to fire more than 2 bullets without reloading

**Comment by ttmahik** [comment]
@LegaSource It would be nice to have a cooldown setting to stun monsters and players, in fact
